[Bug] Get digest
fogbow/saps-engine pull request #125
Opened 2020-04-13 20:15 UTC by thiagoyeds

Fix #115

2020-04-13 23:17 UTC, wesleymonte approved these changes

2020-04-14 12:39 UTC, wesleymonte requested changes
This function is swallow the exception in catch block. Allow the exception to go out.

2020-04-14 19:26 UTC, thiagomanel approved these changes
lgtm

2020-04-14 19:27 UTC, wesleymonte approved these changes

2020-04-14 19:27 UTC, merged