Improvement/endtoend test setup
fogbow/saps-engine pull request #151
Opened 2020-06-01 11:50 UTC by thiagoyeds

Fixed #116

2020-06-15 13:41 UTC, thiagomanel commented on src/main/java/org/fogbowcloud/saps/engine/utils/ExecutionScriptTagUtil.java
> +	protected static String DEFAULT_ENDTOEND_SCRIPT_TAG_JSON_PATH = "resources/execution_endtoend_script_tags.json";
this is something we definitely don't want to add to our code. I'm fine to accept this PR if you add a feature to have a CLI or API to submit scripts

2020-06-15 13:46 UTC, thiagomanel requested changes
thanks @thiagoyeds 
I'm ok to accept this PR but you need first to create an issue as requested on the comment I've submitted

2020-06-15 17:43 UTC, raonismaneoto approved these changes

2020-06-16 14:31 UTC, thiagoyeds commented
Hello @thiagomanel,
I created the requested issue in #154, can you take a look and check if everything is ok?

2020-06-16 15:33 UTC, thiagomanel commented
> Hello @thiagomanel,
> I created the requested issue in #154, can you take a look and check if everything is ok?

Thanks. Now, I'm ok to aprove the PR

2020-06-16 15:34 UTC, thiagomanel approved these changes
lgmt

2020-06-16 15:34 UTC, merged