Creating use case tests for task selection [WIP]
fogbow/saps-engine pull request #50
Opened 2019-11-01 17:05 UTC by ThiagoWhispher

2019-11-03 21:13 UTC, paulofelipefeitosa requested changes
Hi @ThiagoWhispher thank you for the test set, I think that you get it :smile:! Now its time to improve the test code! 

I noticed that there is a lot of duplicated code, in truth the test logic is the same for all test cases: you will provide a test data and then check if the returned value is equal to the expected value, correct? So, I think that we could have just one test code and reuse it with different parameters and expected values, please check [JUnit Parameterized Tests](https://github.com/junit-team/junit4/wiki/parameterized-tests).

2019-11-03 21:13 UTC, paulofelipefeitosa commented on src/test/java/org/fogbowcloud/saps/engine/core/scheduler/SchedulerTest.java
> +			e.printStackTrace();
Please, do not catch an exception just to print the stack trace, just throw it.

2019-11-03 21:13 UTC, paulofelipefeitosa commented on src/test/java/org/fogbowcloud/saps/engine/core/scheduler/SchedulerTest.java
> +	public void testSelectZeroTasksWithZeroCapacitySubmitionWhenThereIsNoAvailableTasks()
_Submition_ is a typo - **Submission**

2019-11-04 12:40 UTC, ThiagoWhispher commented on src/test/java/org/fogbowcloud/saps/engine/core/scheduler/SchedulerTest.java
> +	public void testSelectZeroTasksWithZeroCapacitySubmitionWhenThereIsNoAvailableTasks()
Done

2019-11-04 12:41 UTC, ThiagoWhispher commented on src/test/java/org/fogbowcloud/saps/engine/core/scheduler/SchedulerTest.java
> +			e.printStackTrace();
Done

2019-11-04 12:59 UTC, ThiagoWhispher commented
Thank you @paulofelipefeitosa, I will see your recommendation using JUnit Parameterized Tests and apply to tests.

2019-12-17 20:08 UTC, ThiagoWhispher commented
This PR continues in PR #53

2019-12-17 20:08 UTC, closed without merging